# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:15
from __future__ import unicode_literals

import borrow.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=8, validators=[borrow.validators.validate_postcode])),
                ('registration_number', models.CharField(max_length=8, unique=True, validators=[borrow.validators.validate_crn])),
                ('sector', models.CharField(choices=[('retail', 'Retail'), ('professional_services', 'Professional Services'), ('food_and_drink', 'Food & Drink'), ('entertainment', 'Entertainment')], max_length=24)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the loan', max_digits=10)),
                ('days', models.PositiveSmallIntegerField(help_text='How many days?')),
                ('reason', models.TextField(help_text='Reason for the loan')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('declined', 'Declined'), ('approved', 'Approved')], default='received', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapUserToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_by_admin', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Map Users to Companies',
                'ordering': ['user', 'created_at', 'company'],
                'verbose_name': 'Map User to Company',
            },
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.MapUserToCompany'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, through='borrow.MapUserToCompany', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mapusertocompany',
            unique_together=set([('user', 'company')]),
        ),
    ]
